name: aicompo
version: "0.0.0"
maintainer: Joe Vargas
synopsis: AI Compo
description: AI Compo
stability: experimental
license: MIT
extra-source-files:
- package.yaml
- stack.yaml
- README.md
ghc-options: -Wall
library:
  dependencies:
    - base >= 4.9 && < 5
    - fluid-idl
    - fluid-idl-scotty
    - mtl
    - text
    - safe
    - turn-loop
    - text-conversions
    - random
    - containers
    - lens
    - protolude
  default-extensions:
    - LambdaCase
    - GeneralizedNewtypeDeriving
    - NamedFieldPuns
    - OverloadedStrings
    - FlexibleInstances
    - MultiParamTypeClasses
  source-dirs: src
executables:
  aicompo:
    dependencies:
      - base
      - aicompo
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
      - -Wall
    main: Main.hs
    source-dirs: app
